#!/usr/bin/env python

import argparse
import os
from subprocess import check_call, check_output

from sr.comp.http.manager import update_lock

parser = argparse.ArgumentParser(description = "Update the given compstate repo in a safe manner")
parser.add_argument("compstate", help = "Competition state git repository path")

args = parser.parse_args()

# Fetch first, don't need to lock for this bit
check_call("git fetch origin", shell=True, cwd=args.compstate)

with update_lock(args.compstate):
    check_output("git checkout origin/master", shell=True, cwd=args.compstate)
